Wersja v1 dokumentacji do zaakceptowania
bot-wheels/docs pull request #61
Opened 2024-12-21 22:56 UTC by Assassin-PL

Closes #58

2024-12-22 19:13 UTC, D-Mielewczyk commented
Hej, dodaj proszę dokładne ścieżki do tych plików.

Musi też być napisane jak odpalić trening z następującymi opcjami:
- tryb gry (bot czy człowiek)
- jak podać config (to chyba już jest)
- liczba botów
- jak włączyć tu wizualizacje (jeżeli nie wiesz zgłoszę inną osobę żeby to dopisała)

tak samo musi być opisane jak włączyć po prostu gameplay już wytrenowanego modelu z tymi samymi opcjami

2024-12-22 19:13 UTC, D-Mielewczyk requested changes
Hej, dodaj proszę dokładne ścieżki do tych plików.

Musi też być napisane jak odpalić trening z następującymi opcjami:
- tryb gry (bot czy człowiek)
- jak podać config (to chyba już jest)
- liczba botów
- jak włączyć tu wizualizacje (jeżeli nie wiesz zgłoszę inną osobę żeby to dopisała)

tak samo musi być opisane jak włączyć po prostu gameplay już wytrenowanego modelu z tymi samymi opcjami

2025-01-04 19:06 UTC, D-Mielewczyk commented
@Assassin-PL

2025-01-04 22:39 UTC, Assassin-PL commented
@D-Mielewczyk liczba ja robilem tylko zeby 1 vs 1 mecz sie odpalil i bylo wszystko pod tym katem projektowane, inna osoba miala zz zadanie odpalic kilka botow w 1 grze na raz, Tryb gry i wszystkie rzeczy sa podawane w config.cfg, z wizualizacja zglos inna osobe bo to jest sam trening bota, wszystkie dostepne parametry sa w pliku .config do ustawinia i zawsze plik config jest czytany przy inicalizacji obiektu i zawiera wsyzstkie parametry dla bota

2025-01-06 22:00 UTC, D-Mielewczyk approved these changes

2025-01-06 22:01 UTC, merged